name: Check Update

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Run check_update script
      run: |
        chmod +x ./check_update.sh
        ./check_update.sh

    - name: Push changes
      if: success()
      uses: ad-m/github-push-action@v0.5.0
      with:
        branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Push tags
      if: success()
      run: |
        git tag -a v${{ github.run_number }} -m "Version ${{ github.run_number }}"
        git push origin v${{ github.run_number }}
